"""Add organism_key to Taxon

Revision ID: ee5121abc575
Revises: 
Create Date: 2025-03-11 12:18:53.465426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee5121abc575'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### Commands manually inserted. ###

    # Clear the taxon table so that it will be rebuilt with the organism
    # field popultated.
    op.execute('DELETE FROM taxon')
    # ### End manually inserted commands ###

    # ### Commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'taxon',
        sa.Column(
            'organism_key',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False
        )
    )
    op.create_index(
        op.f('ix_taxon_organism_key'),
        'taxon',
        ['organism_key'],
        unique=False
    )
    # ### End Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxon_organism_key'), table_name='taxon')
    op.drop_column('taxon', 'organism_key')
    # ### end Alembic commands ###
