"""Add Usage table

Revision ID: 986c3cf5f0df
Revises: a7cf946c1d72
Create Date: 2026-03-05 10:42:46.497664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '986c3cf5f0df'
down_revision: Union[str, None] = 'a7cf946c1d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('verification_requests', sa.Integer(), nullable=False),
    sa.Column('validation_requests', sa.Integer(), nullable=False),
    sa.Column('verification_records', sa.Integer(), nullable=False),
    sa.Column('validation_records', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_name'], ['user.name'], name=op.f('fk_usage_user_name_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage'))
    )
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_user_name'), ['user_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_user_name'))

    op.drop_table('usage')
    # ### end Alembic commands ###
