name: Push and Pull request workflow

on:
  pull_request:
    branches:
        - main
  push:
    branches: 
        - main
        - dev
      
jobs:
    call-build-and-test:
        uses: ./.github/workflows/reuse-build-and-test.yml