on:
  push:
    branches: [ $default-branch ]

jobs:
    call-build-and-test:
        uses: ./.github/workflows/reuse-build-and-test.yml
    call-publish:
        uses: ./.github/workflows/reuse-publish.yml