name: Tag workflow

on:
  push:
    tags: 
        - 'v*'

jobs:
    call-build-and-test:
        uses: ./.github/workflows/reuse-build-and-test.yml
    call-publish:
        needs: call-build-and-test
        uses: ./.github/workflows/reuse-publish.yml